<a href="https://colab.research.google.com/github/hernans7/mis433/blob/main/Copy_of_assignment_IMDB_manipulation_summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - Analyzing the IMDB Top 1000 Movies

In the next few assignments, you will be working with this data set of IMDB top 1000 movies.

Source: https://www.kaggle.com/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

In [19]:
import pandas as pd
import numpy as np

To read the data file from your Google Drive, mount your drive first.

In [20]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [23]:
imdb = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/samanthahernandezramirez_imdb_top_1000.csv', header=0)
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [24]:
import os

# List contents of your Google Drive's MyDrive folder
# If your file is in a subdirectory, you may need to adjust this path.
print(os.listdir('/content/drive/MyDrive'))

# Or to search specifically for the file
# for root, dirs, files in os.walk('/content/drive/MyDrive'):
#     if 'imdb_top_1000.csv' in files:
#         print(f"Found 'imdb_top_1000.csv' at: {os.path.join(root, 'imdb_top_1000.csv')}")

['Colab Notebooks', 'QuickShare_2404181418.zip', 'QuickShare_2404181418.zip (Unzipped Files)', 'River Otter Research Paper draft.docx', 'Samantha Hernandez- Application for Employment BGCC Pool.gdoc', 'Untitled document.gdoc', 'SHR Resume 2025.docx', 'ACCT 240 Final Exam Study Sheet.gdoc', 'Ring Request.gform', '53EE76E5-B6E6-41BC-A79F-0996AFF58A18.jpeg', 'IMG_0420.png', 'IMG_0421.png', 'IMG_0422.png', 'Samantha Hernandez Ramirez.gsite']

In [25]:
# Describe the dataframe using the info() method.
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [26]:
# List all the column names:
imdb.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

## Part 1: Data Manipulation

In [28]:
# Display top 10 movies' title, released year and IMDB rating.
imdb[['Series_Title', 'Released_Year', 'IMDB_Rating']].head(10)

                                    Series_Title Released_Year  IMDB_Rating
0                       The Shawshank Redemption          1994          9.3
1                                  The Godfather          1972          9.2
2                                The Dark Knight          2008          9.0
3                         The Godfather: Part II          1974          9.0
4                                   12 Angry Men          1957          9.0
5  The Lord of the Rings: The Return of the King          2003          8.9
6                                   Pulp Fiction          1994          8.9
7                               Schindler's List          1993          8.9
8                                      Inception          2010          8.8
9                                     Fight Club          1999          8.8

In [30]:
# Display movies ranked 11-20.
# Show their title, released year and IMDB rating.
imdb[['Series_Title', 'Released_Year', 'IMDB_Rating']].head(11-20)

                           Series_Title Released_Year  IMDB_Rating
0              The Shawshank Redemption          1994          9.3
1                         The Godfather          1972          9.2
2                       The Dark Knight          2008          9.0
3                The Godfather: Part II          1974          9.0
4                          12 Angry Men          1957          9.0
..                                  ...           ...          ...
986                      Watership Down          1978          7.6
987                    Midnight Express          1978          7.6
988  Close Encounters of the Third Kind          1977          7.6
989                    The Long Goodbye          1973          7.6
990                        Giù la testa          1971          7.6

[991 rows x 3 columns]

In [31]:
# Select all movies directed by Quentin Tarantino.
# Show their title, released year, IMDB rating, and gross.
tarantino_movies = imdb[imdb['Director'] == 'Quentin Tarantino']
display(tarantino_movies[['Series_Title', 'Released_Year', 'IMDB_Rating', 'Gross']])

                         Series_Title Released_Year  IMDB_Rating        Gross
6                        Pulp Fiction          1994          8.9  107,928,762
62                   Django Unchained          2012          8.4  162,805,434
93               Inglourious Basterds          2009          8.3  120,540,719
103                    Reservoir Dogs          1992          8.3    2,832,029
241                 Kill Bill: Vol. 1          2003          8.1   70,099,045
369                 Kill Bill: Vol. 2          2004          8.0   66,208,183
584                 The Hateful Eight          2015          7.8   54,117,416
879  Once Upon a Time... in Hollywood          2019          7.6  142,502,728

In [32]:
# Select all R rated movies with IMDB_Rating>=8.5
# Show their title, released year, certificate, and IMDB rating.
r_rated_high_imdb = imdb[(imdb['Certificate'] == 'R') & (imdb['IMDB_Rating'] >= 8.5)]
display(r_rated_high_imdb[['Series_Title', 'Released_Year', 'Certificate', 'IMDB_Rating']])

           Series_Title Released_Year Certificate  IMDB_Rating
24  Saving Private Ryan          1998           R          8.6
38          The Pianist          2002           R          8.5
40   American History X          1998           R          8.5

In [33]:
# How many unique values are there in the column "Released_Year"?
# Hint: nunique()
imdb['Released_Year'].nunique()

100

In [34]:
# Count the number of movies in each "Released_Year"?
# Hint: value_counts()
imdb['Released_Year'].value_counts()

Released_Year
2014    32
2004    31
2009    29
2013    28
2016    28
        ..
1920     1
1930     1
1922     1
1943     1
PG       1
Name: count, Length: 100, dtype: int64

In [35]:
# In this dataset, there is a movie with an error in "Released_Year".
# Hint: Released_Year should be a 4-digit integer but this movie's is not.
# Find this movie.

# Find rows where 'Released_Year' is not numeric
# The error in 'Released_Year' is 'PG', so we look for that specific value.
error_movie = imdb[imdb['Released_Year'] == 'PG']
display(error_movie)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [36]:
# Correct the values for the corresponding columns ("Released_Year" and "Certificate").
# You may want to look up this movie on www.imdb.com.
# Hint: You can set value for a particular row by: df.loc[row_name, column_name] = new_value

# Correct the 'Released_Year' and 'Certificate' for 'Apollo 13'
imdb.loc[imdb['Series_Title'] == 'Apollo 13', 'Released_Year'] = '1995'
imdb.loc[imdb['Series_Title'] == 'Apollo 13', 'Certificate'] = 'PG'

# Verify the correction
display(imdb[imdb['Series_Title'] == 'Apollo 13'])

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,1995,PG,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [37]:
imdb['Released_Year'] = imdb['Released_Year'].astype(int)

# Verify the change
display(imdb.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   int64
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 125.1+ KB

None

In [38]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, certificate, and IMDB rating.
high_rated_recent_movies = imdb[(imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5)]
display(high_rated_recent_movies[['Series_Title', 'Released_Year', 'Certificate', 'IMDB_Rating']])

        Series_Title  Released_Year Certificate  IMDB_Rating
8          Inception           2010          UA          8.8
18          Hamilton           2020       PG-13          8.6
19      Gisaengchung           2019           A          8.6
20   Soorarai Pottru           2020           U          8.6
21      Interstellar           2014          UA          8.6
33             Joker           2019           A          8.5
34          Whiplash           2014           A          8.5
35  The Intouchables           2011          UA          8.5

In [39]:
# Select all movies whose genres contain 'Animation'
animation_movies = imdb[imdb['Genre'].str.contains('Animation', case=False, na=False)]
display(animation_movies[['Series_Title', 'Released_Year', 'Genre', 'IMDB_Rating']])

,Series_Title,Released_Year,Genre,IMDB_Rating
23,Sen to Chihiro no kamikakushi,2001,"Animation, Adventure, Family",8.6
43,The Lion King,1994,"Animation, Adventure, Drama",8.5
46,Hotaru no haka,1988,"Animation, Drama, War",8.5
56,Kimi no na wa.,2016,"Animation, Drama, Fantasy",8.4
58,Spider-Man: Into the Spider-Verse,2018,"Animation, Action, Adventure",8.4
...,...,...,...,...
956,Mulan,1998,"Animation, Adventure, Family",7.6
971,Omohide poro poro,1991,"Animation, Drama, Romance",7.6
976,The Little Mermaid,1989,"Animation, Family, Fantasy",7.6
986,Watership Down,1978,"Animation, Adventure, Drama",7.6
992,The Jungle Book,1967,"Animation, Adventure, Family",7.6

In [40]:
# Create a new dataframe called "stars" including the following columns:
# Series_Title, Released_Year, Star1, Star2, Star3, Star4
stars = imdb[['Series_Title', 'Released_Year', 'Star1', 'Star2', 'Star3', 'Star4']]
display(stars.head())

,Series_Title,Released_Year,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,1972,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,2008,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,1974,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,1957,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler

In [41]:
# Create a new dataframe called "genres" including the following columns:
# Series_Title, Released_Year, Genre.
genres = imdb[['Series_Title', 'Released_Year', 'Genre']]
display(genres.head())

               Series_Title  Released_Year                 Genre
0  The Shawshank Redemption           1994                 Drama
1             The Godfather           1972          Crime, Drama
2           The Dark Knight           2008  Action, Crime, Drama
3    The Godfather: Part II           1974          Crime, Drama
4              12 Angry Men           1957          Crime, Drama

In [42]:
# Sorting:
# Sort dataframe genres in ascending order of "Released_Year"
genres_sorted_by_year = genres.sort_values(by='Released_Year', ascending=True)
display(genres_sorted_by_year.head())

                     Series_Title  Released_Year                     Genre
321  Das Cabinet des Dr. Caligari           1920  Fantasy, Horror, Mystery
127                       The Kid           1921     Comedy, Drama, Family
568                     Nosferatu           1922           Fantasy, Horror
194                  Sherlock Jr.           1924   Action, Comedy, Romance
193                 The Gold Rush           1925  Adventure, Comedy, Drama

In [ ]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"

high_rated_recent_movies_gross = imdb[(imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5)]

# Note: Sorting 'Gross' might not work correctly yet, as it's an object type with commas and dollar signs.
# This will be addressed in the next steps.
display(high_rated_recent_movies_gross[['Series_Title', 'Released_Year', 'Certificate', 'Gross']].sort_values(by='Gross', ascending=False))

In [ ]:
# Does the sorting result look right to you? What's the problem?
###No beacuse the gross colum is currently an object type

In [43]:
# Resolve this problem of "Gross" and convert its data type to float
# Hint: You may find this webpage useful:
# https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-column-of-a-pandas-dataframe

# Remove commas from the 'Gross' column and convert to numeric, coercing errors to NaN
imdb['Gross'] = imdb['Gross'].str.replace(',', '', regex=False).astype(float)

# Verify the change
display(imdb.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   int64
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    float64
dtypes: float64(3), int64(2), object(11)
memory usage: 125.1+ KB

None

In [44]:
# Next, redo the sorting on Gross

# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"

high_rated_recent_movies_gross = imdb[(imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5)]
display(high_rated_recent_movies_gross[['Series_Title', 'Released_Year', 'Certificate', 'Gross']].sort_values(by='Gross', ascending=False))

        Series_Title  Released_Year Certificate        Gross
33             Joker           2019           A  335451311.0
8          Inception           2010          UA  292576195.0
21      Interstellar           2014          UA  188020017.0
19      Gisaengchung           2019           A   53367844.0
35  The Intouchables           2011          UA   13182281.0
34          Whiplash           2014           A   13092000.0
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [ ]:
# Add a new column "Runtime_min" by removing the substring " min" in "Runtime"
# Set its data type as int
# Hint: https://stackoverflow.stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe

imdb['Runtime_min'] = imdb['Runtime'].str.replace(' min', '', regex=False).astype(int)

# Verify the change
display(imdb[['Runtime', 'Runtime_min']].head())

In [45]:
# Add a new column "Age_Year" by expression: Current year - Released_Year
import datetime
current_year = datetime.datetime.now().year
imdb['Age_Year'] = current_year - imdb['Released_Year']

# Verify the change
display(imdb[['Series_Title', 'Released_Year', 'Age_Year']].head())

               Series_Title  Released_Year  Age_Year
0  The Shawshank Redemption           1994        32
1             The Godfather           1972        54
2           The Dark Knight           2008        18
3    The Godfather: Part II           1974        52
4              12 Angry Men           1957        69

In [46]:
# Add a new column "Decade" with values as 1980, 1990, 2000, 2010, 2020, etc.
imdb['Decade'] = (imdb['Released_Year'] // 10) * 10

# Verify the change
display(imdb[['Series_Title', 'Released_Year', 'Decade']].head())

               Series_Title  Released_Year  Decade
0  The Shawshank Redemption           1994    1990
1             The Godfather           1972    1970
2           The Dark Knight           2008    2000
3    The Godfather: Part II           1974    1970
4              12 Angry Men           1957    1950

## Part 2: Data Summarization

In [47]:
total_gross = imdb['Gross'].sum()
display(f"Total Gross of all top 1000 movies: ${total_gross:,.2f}")

'Total Gross of all top 1000 movies: $56,536,877,976.00'

In [48]:
average_votes = imdb['No_of_Votes'].mean()
display(f"Average number of votes for all movies: {average_votes:,.2f}")

'Average number of votes for all movies: 273,692.91'

In [50]:
# Count movies in each decade (e.g., ..., 1980, 1990, 2000, 2010, 2020)
# Sort decades by the number of movies in descending order
decade_counts = imdb['Decade'].value_counts().sort_values(ascending=False)
display(decade_counts)

Decade
2010    242
2000    237
1990    151
1980     89
1970     76
1960     73
1950     56
1940     35
1930     24
1920     11
2020      6
Name: count, dtype: int64

In [51]:
# Count movies by different directors.
# Show the top 10 directors with the most movies in this list
top_directors = imdb['Director'].value_counts().head(10)
display(top_directors)

Director
Alfred Hitchcock     14
Steven Spielberg     13
Hayao Miyazaki       11
Akira Kurosawa       10
Martin Scorsese      10
Woody Allen           9
Stanley Kubrick       9
Billy Wilder          9
Clint Eastwood        8
Christopher Nolan     8
Name: count, dtype: int64

In [52]:
# For each director, calculate the number of movies, average IMDB_Rating, and total gross.
# Ranked in descending order of total gross
# Show the top 10 directors with the most gross
director_summary = imdb.groupby('Director').agg(
    num_movies=('Series_Title', 'count'),
    average_imdb_rating=('IMDB_Rating', 'mean'),
    total_gross=('Gross', 'sum')
).sort_values(by='total_gross', ascending=False)
display(director_summary.head(10))

                   num_movies  average_imdb_rating   total_gross
Director
Steven Spielberg           13             8.030769  2.478133e+09
Anthony Russo               4             8.075000  2.205039e+09
Christopher Nolan           8             8.462500  1.937454e+09
James Cameron               5             8.080000  1.748237e+09
Peter Jackson               5             8.400000  1.597312e+09
J.J. Abrams                 3             7.833333  1.423171e+09
Brad Bird                   4             7.900000  1.099628e+09
Robert Zemeckis             5             8.120000  1.049446e+09
David Yates                 3             7.800000  9.789537e+08
Pete Docter                 4             8.125000  9.393821e+08

In [53]:
director_decade_summary = imdb.groupby(['Decade', 'Director']).agg(
    num_movies=('Series_Title', 'count'),
    average_imdb_rating=('IMDB_Rating', 'mean')
).sort_values(by='num_movies', ascending=False)
display(director_decade_summary.head())

                         num_movies  average_imdb_rating
Decade Director
1950   Billy Wilder               6             8.133333
       Akira Kurosawa             5             8.260000
2010   Denis Villeneuve           5             7.980000
1950   Alfred Hitchcock           5             8.220000
1980   Steven Spielberg           5             7.980000

In [56]:
# Find the top 3 highest rated movies of each year since 2010.
# Show their released year, ranking, title, and IMDB_Rating.
# Sort them in descending order of year and ascending order of ranking

# Filter movies released since 2010
movies_since_2010 = imdb[imdb['Released_Year'] >= 2010]

# Group by Released_Year and find the top 3 highest rated movies for each year
top_movies_by_year = movies_since_2010.groupby('Released_Year').apply(
    lambda x: x.nlargest(3, 'IMDB_Rating', keep='first')
).reset_index(drop=True)

# Add a 'Ranking' column within each year
top_movies_by_year['Ranking'] = top_movies_by_year.groupby('Released_Year')['IMDB_Rating'].rank(ascending=False).astype(int)

# Select and sort the desired columns
result = top_movies_by_year[['Released_Year', 'Ranking', 'Series_Title', 'IMDB_Rating']]
result = result.sort_values(by=['Released_Year', 'Ranking'], ascending=[False, True])

display(result)

/tmp/ipykernel_13219/734092836.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_movies_by_year = movies_since_2010.groupby('Released_Year').apply(

    Released_Year  Ranking                       Series_Title  IMDB_Rating
30           2020        1                           Hamilton          8.6
31           2020        1                    Soorarai Pottru          8.6
32           2020        3                               Soul          8.1
27           2019        1                       Gisaengchung          8.6
28           2019        2                              Joker          8.5
29           2019        3                  Avengers: Endgame          8.4
24           2018        2                         Capharnaüm          8.4
25           2018        2  Spider-Man: Into the Spider-Verse          8.4
26           2018        2             Avengers: Infinity War          8.4
21           2017        2          Ayla: The Daughter of War          8.4
22           2017        2                       Vikram Vedha          8.4
23           2017        2                               Coco          8.4
18           2016        1                     Kimi no na wa.          8.4
19           2016        1                             Dangal          8.4
20           2016        3                               Pink          8.1
15           2015        1                             Talvar          8.2
16           2015        1                           Drishyam          8.2
17           2015        3                               Room          8.1
12           2014        1                       Interstellar          8.6
13           2014        2                           Whiplash          8.5
14           2014        3                              Mommy          8.1
9            2013        1                           Drishyam          8.3
10           2013        2                              Queen          8.2
11           2013        2                        Mandariinid          8.2
6            2012        1                   Django Unchained          8.4
7            2012        1              The Dark Knight Rises          8.4
8            2012        3                             Jagten          8.3
3            2011        1                   The Intouchables          8.5
4            2011        2            Jodaeiye Nader az Simin          8.3
5            2011        3                            Warrior          8.2
0            2010        1                          Inception          8.8
1            2010        2                          Incendies          8.3
2            2010        3                              Udaan          8.2

In [57]:
# Find all directors whose movies appeared in at least five different decades.
# Your result should include: director, decade, and the number of movies in the decade.

# Group by director and decade, then count the number of movies
director_decade_counts = imdb.groupby(['Director', 'Decade']).agg(
    num_movies=('Series_Title', 'count')
).reset_index()

# Count the number of unique decades each director has movies in
decades_per_director = director_decade_counts.groupby('Director')['Decade'].nunique()

# Filter for directors who have movies in at least 5 different decades
directors_five_decades = decades_per_director[decades_per_director >= 5].index

# Filter the original director_decade_counts to include only these directors
result = director_decade_counts[director_decade_counts['Director'].isin(directors_five_decades)]

# Sort the results for better readability
result = result.sort_values(by=['Director', 'Decade'])

display(result)

             Director  Decade  num_movies
247    Hayao Miyazaki    1970           1
248    Hayao Miyazaki    1980           4
249    Hayao Miyazaki    1990           2
250    Hayao Miyazaki    2000           3
251    Hayao Miyazaki    2010           1
424   Martin Scorsese    1970           1
425   Martin Scorsese    1980           3
426   Martin Scorsese    1990           2
427   Martin Scorsese    2000           1
428   Martin Scorsese    2010           3
644  Steven Spielberg    1970           2
645  Steven Spielberg    1980           5
646  Steven Spielberg    1990           3
647  Steven Spielberg    2000           2
648  Steven Spielberg    2010           1

In [58]:
# Question 1: What is the average runtime (in minutes) for movies in each genre?
# Your result should include: Genre and Average Runtime.

average_runtime_by_genre = imdb.groupby('Genre')['Runtime_min'].mean().reset_index()
display(average_runtime_by_genre.sort_values(by='Runtime_min', ascending=False))

KeyError: 'Column not found: Runtime_min'

In [59]:
# Question 2: Is there a correlation between IMDB_Rating and Gross revenue?
# Hint: Use the .corr() method after dropping NaN values.

correlation = imdb['IMDB_Rating'].corr(imdb['Gross'])
display(f"The correlation between IMDB_Rating and Gross revenue is: {correlation:.2f}")

'The correlation between IMDB_Rating and Gross revenue is: 0.10'